services:
  rust:
    container_name: rust
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 104:104
    tty: true
    stdin_open: true
