services:
  db:
    image: postgres:18-alpine
    container_name: oceanus-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oceanus}
      POSTGRES_USER: ${POSTGRES_USER:-oceanus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-oceanus}
    ports:
      - "5432:5432"
    volumes:
      - oceanus-volume:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - default

volumes:
  oceanus-volume:
    name: oceanus-volume

networks:
  default:
    name: oceanus-network
