[package]
name = "dicom-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
phf.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
