[workspace]
resolver = "3"
members = [
    "dicom-server",
]

[workspace.package]
version = "0.0.0"
authors = ["Yamato SHINOZUKA <shino0526y@gmail.com>"]
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
